import pandas as pd
from transformers import AutoTokenizer
from datasets import Dataset

data = {
    "title": [
        "Pride and Prejudice", "Moby Dick", "The Great Gatsby", "1984", "To Kill a Mockingbird",
        "The Catcher in the Rye", "Brave New World", "The Lord of the Rings", "Harry Potter and the Sorcerer's Stone",
        "Jane Eyre", "The Hobbit", "Fahrenheit 451", "The Picture of Dorian Gray", "Crime and Punishment",
        "The Brothers Karamazov", "The Odyssey", "The Iliad", "War and Peace", "Anna Karenina",
        "Great Expectations", "Dracula", "Frankenstein", "The Alchemist", "Wuthering Heights",
        "The Count of Monte Cristo", "Les Misérables", "Don Quixote", "Madame Bovary", "The Divine Comedy",
        "The Kite Runner", "Memoirs of a Geisha", "The Da Vinci Code", "A Tale of Two Cities",
        "One Hundred Years of Solitude", "Slaughterhouse-Five", "Catch-22", "Of Mice and Men", "Beloved",
        "The Shining", "The Road", "Gone with the Wind", "The Hunger Games", "Dune", "The Handmaid's Tale",
        "The Secret Garden", "The Girl with the Dragon Tattoo", "The Maze Runner", "Percy Jackson & the Olympians",
        "Ender's Game", "The Night Circus", "The Book Thief", "Life of Pi", "The Time Traveler's Wife",
        "The Fault in Our Stars", "The Help", "Water for Elephants", "The Giver", "Divergent", "The Outsiders",
        "A Wrinkle in Time", "The Goldfinch", "Shogun", "The Pillars of the Earth", "The Poisonwood Bible",
        "The Godfather", "Good Omens", "Atonement", "The Lovely Bones", "The Girl on the Train", "Big Little Lies",
        "American Gods", "The Lightning Thief", "Room", "The Silent Patient", "The Institute",
        "The Girl Who Played with Fire", "Sharp Objects", "The Rosie Project", "Circe", "The Nightingale", 
        "Red Queen", "The Power"
    ],
    "plot": [
        "The story of Elizabeth Bennet as she navigates love and family dynamics in 19th-century England.",
        "The epic tale of Captain Ahab's obsessive quest to hunt down the great white whale, Moby Dick.",
        "A mysterious millionaire, Jay Gatsby, hosts extravagant parties in hopes of reuniting with his lost love.",
        "In a dystopian future, Winston Smith struggles under the oppressive rule of a totalitarian regime.",
        "Scout Finch grows up in the racially charged American South, learning valuable lessons about justice and morality.",
        "Holden Caulfield, a disillusioned teenager, roams New York after being expelled from prep school.",
        "In a futuristic world, society is divided and controlled, but one man, Bernard Marx, seeks more freedom.",
        "Frodo Baggins embarks on a perilous journey to destroy the One Ring and save Middle-earth.",
        "Young Harry Potter learns he is a wizard and must face the dark forces that threaten the magical world.",
        "Jane Eyre, an orphan, grows up facing harsh treatment and eventually finds love while overcoming personal struggles.",
        "Bilbo Baggins, a hobbit, is thrust into an adventure to help dwarves reclaim their kingdom from a dragon.",
        "In a society where books are banned, Guy Montag, a fireman, begins questioning the purpose of his work.",
        "Dorian Gray remains youthful while a portrait of him ages, reflecting his moral decay.",
        "Raskolnikov, a poor student, commits murder and wrestles with his conscience in St. Petersburg.",
        "Three brothers grapple with faith, morality, and the legacy of their father's sins in this Russian epic.",
        "Odysseus embarks on a long journey home after the Trojan War, facing many obstacles along the way.",
        "The Greek hero Achilles takes part in the Trojan War, seeking glory but ultimately facing tragedy.",
        "The lives of five aristocratic families intersect during Napoleon's invasion of Russia.",
        "Anna Karenina, trapped in a loveless marriage, pursues a tragic love affair with a young officer.",
        "Pip, an orphan, dreams of becoming a gentleman and learning the true nature of love and loyalty.",
        "Jonathan Harker discovers the terrifying truth about Count Dracula, a vampire seeking to spread his curse.",
        "Victor Frankenstein creates a living being, only to be horrified by the consequences of playing God.",
        "Santiago, an Andalusian shepherd, goes on a journey to discover his personal legend and treasure.",
        "Heathcliff and Catherine's intense, destructive relationship plays out on the Yorkshire moors.",
        "Edmond Dantès is wrongfully imprisoned and embarks on a quest for revenge after escaping prison.",
        "Jean Valjean, an ex-convict, seeks redemption amid the political upheavals of post-revolutionary France.",
        "Don Quixote, a man obsessed with chivalric ideals, embarks on misguided adventures with his loyal squire.",
        "Madame Bovary, bored with provincial life, seeks escape through romantic fantasies that lead to her downfall.",
        "Dante journeys through Hell, Purgatory, and Heaven in this epic allegory of the soul's path to God.",
        "Amir recalls his childhood in Afghanistan and his complicated relationship with his best friend, Hassan.",
        "A Japanese woman reflects on her difficult journey from being sold into servitude to becoming a renowned geisha.",
        "Robert Langdon uncovers a secret society while solving a murder mystery related to religious symbols.",
        "The French Revolution brings together the lives of Charles Darnay and Sydney Carton, who both love the same woman.",
        "Magical realism tells the multi-generational story of the Buendía family in the fictional town of Macondo.",
        "Billy Pilgrim, an optometrist, becomes 'unstuck in time' as he recalls his experiences in World War II.",
        "Captain John Yossarian tries to survive the absurdities and horrors of war while facing bureaucratic madness.",
        "George and Lennie, displaced ranch workers during the Great Depression, dream of owning their own farm.",
        "Sethe, an escaped slave, is haunted by her traumatic past and the ghost of her dead daughter.",
        "A family isolated in a haunted hotel during the winter faces terrifying supernatural forces and personal madness.",
        "A father and son journey through a post-apocalyptic landscape, struggling to survive and maintain their humanity.",
        "Scarlett O'Hara's life is upended by the American Civil War as she struggles to maintain her family's plantation.",
        "In a dystopian future, Katniss Everdeen volunteers for a deadly televised competition to protect her sister.",
        "On the desert planet Arrakis, Paul Atreides navigates politics, prophecy, and survival in an epic saga.",
        "In a totalitarian society, Offred serves as a 'Handmaid' in a dystopian future where women's rights are suppressed.",
        "Orphan Mary Lennox discovers a hidden, neglected garden and restores it, transforming her life in the process.",
        "A journalist teams up with an unusual hacker to uncover a mystery surrounding a powerful family in Sweden.",
        "A group of teens must navigate a deadly maze in this thrilling dystopian adventure.",
        "Percy Jackson discovers he is a demigod and embarks on a quest to prevent a war among the Greek gods.",
        "A brilliant young boy is recruited to fight an alien race in a war that will determine humanity's future.",
        "Two magicians duel in a magical circus that appears only at night, while their destinies become intertwined.",
        "A young girl steals books to survive the harsh realities of life during Nazi Germany's regime.",
        "A young boy survives a shipwreck and forms a strange relationship with a tiger while stranded in the Pacific Ocean.",
        "A man with a genetic disorder that causes him to time travel falls in love with a woman in this unique love story.",
        "Two teens, both battling terminal illnesses, find love and meaning in the face of death.",
        "In the 1960s South, an aspiring writer tells the stories of African-American maids working for white families.",
        "A veterinary student joins a traveling circus during the Great Depression and falls in love.",
        "In a controlled, colorless society, Jonas receives the memories of the past and begins to question everything.",
        "In a future Chicago, Tris Prior must choose between five factions that define their society.",
        "A group of teens struggles with growing up, friendship, and violence in this coming-of-age story.",
        "A young girl, her brother, and a friend travel through space and time to rescue her father from a dark force.",
        "After surviving a terrorist attack, a boy grows up facing trauma and an obsession with a stolen painting.",
        "An English navigator is shipwrecked in Japan and becomes involved in the country's political intrigue.",
        "In medieval England, the construction of a cathedral serves as the backdrop for a story of love and conflict.",
        "A missionary family moves to the Congo and faces cultural clashes and personal tragedies.",
        "An Italian-American family rises to power in the world of organized crime.",
        "A demon and an angel must work together to prevent the apocalypse in this humorous fantasy tale.",
        "A woman reflects on the consequences of a lie she told as a child, which altered the course of many lives.",
        "After her murder, a girl narrates the investigation and aftermath from the afterlife.",
        "A woman becomes obsessed with uncovering the truth about another woman's disappearance.",
        "The lives of three women unravel in a beach town, leading to shocking secrets being revealed.",
        "Shadow Moon is drawn into a conflict between old and new gods in this dark and imaginative tale.",
        "Percy Jackson embarks on a quest to recover Zeus's stolen lightning bolt in the modern world.",
        "A kidnapped woman forms a bond with her captor while plotting her escape from his secluded room.",
        "A psychologist becomes obsessed with a mute patient who may hold the key to a mysterious crime.",
        "A boy with psychic abilities is held captive in a mysterious institute where strange experiments are conducted.",
        "The sequel to 'The Girl with the Dragon Tattoo' follows Lisbeth Salander as she uncovers more secrets.",
        "A journalist returns to her hometown to investigate a series of brutal murders in this dark thriller.",
        "A socially awkward man embarks on a quest to find love using a scientific approach.",
        "The story of the goddess Circe, exiled to an island, where she discovers her powers and faces gods and mortals.",
        "During World War II, two sisters in occupied France fight against the Nazis in different ways.",
        "In a world where some people have dangerous powers, a young girl fights for her survival and freedom.",
        "A world where women develop the ability to generate electricity, leading to shifts in societal power."
    ]
}

df = pd.DataFrame(data)

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(example):
    return tokenizer(example["plot"], padding="max_length", truncation=True)

hf_dataset = Dataset.from_pandas(df)
tokenized_dataset = hf_dataset.map(tokenize_function, batched=True)